language: python
dist: trusty
sudo: false

python:
  - "3.6"
  - "nightly"

install:
   - ./setup.py develop
   - pip3 install git+git://github.com/PyCQA/pylint.git@56daa5c3a0d2d6592c673c2932c354b68679997f
   - pip3 install git+git://github.com/PyCQA/astroid.git@313c0c34100118be87164214bd22b226a748166d

script:
  - cd tests
  - pytest --verbose --tb=native
  - cd ..
  - pylint asks tests/*.py

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net#8banana"
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
